### ISSUE TITLE
Oh no, where's Rees on OO?

### ISSUE THREAD

**Issue by cwebber** [jar398/mumble-net-jar#1]
[Rees on OO](http://mumble.net/~jar/articles/oo.html) seems to have disappeared, which is too bad!  It's a great article!

The [Internet Archive](https://web.archive.org/web/20160311212643/http://mumble.net/~jar/articles/oo.html) has a backup copy, pleasantly.

**Comment by jar398** [comment]
It's on Paul Graham's site too (but without the discussion at the end).

But I'll put it back. There was too much junk on the site, so I pushed it aside (still there, but under an unadvertised URL).

**Comment by jar398** [comment]
Reinstated.
